//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CURDMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BhaktDetail
    {
        public int BhaktId { get; set; }
        public string BhaktName { get; set; }
        public string DMV { get; set; }
        public Nullable<int> MobileNo { get; set; }
        public string Gender { get; set; }
    }
}
